
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package scanner.lexer;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LBRACKET = 4;
  public static final int ASSIGNMENT = 29;
  public static final int EQUALS = 15;
  public static final int XOR = 24;
  public static final int LPAREN = 2;
  public static final int MINUS = 7;
  public static final int GREATER_THAN = 17;
  public static final int CHARACTER = 33;
  public static final int RPAREN = 3;
  public static final int NOT = 23;
  public static final int AND = 22;
  public static final int DIV_EQUALS = 13;
  public static final int OR = 21;
  public static final int RESERVED_WORDS = 35;
  public static final int SHIFT_RIGHT_EQUALS = 28;
  public static final int TIMES_EQUALS = 14;
  public static final int DIV = 8;
  public static final int PLUS = 6;
  public static final int GREATER_EQUALS_THAN = 19;
  public static final int EOF = 0;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int NUMBER = 30;
  public static final int MOD = 10;
  public static final int SHIFT_LEFT = 25;
  public static final int MINUS_EQUALS = 12;
  public static final int REAL = 31;
  public static final int SHIFT_LEFT_EQUALS = 27;
  public static final int TIMES = 9;
  public static final int NOT_EQUALS = 16;
  public static final int PLUS_EQUALS = 11;
  public static final int STRING = 32;
  public static final int GREATER_LESS_THAN = 20;
  public static final int LESS_THAN = 18;
  public static final int SHIFT_RIGHT = 26;
  public static final int IDENTIFIER = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "PLUS",
  "MINUS",
  "DIV",
  "TIMES",
  "MOD",
  "PLUS_EQUALS",
  "MINUS_EQUALS",
  "DIV_EQUALS",
  "TIMES_EQUALS",
  "EQUALS",
  "NOT_EQUALS",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_EQUALS_THAN",
  "GREATER_LESS_THAN",
  "OR",
  "AND",
  "NOT",
  "XOR",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "SHIFT_LEFT_EQUALS",
  "SHIFT_RIGHT_EQUALS",
  "ASSIGNMENT",
  "NUMBER",
  "REAL",
  "STRING",
  "CHARACTER",
  "IDENTIFIER",
  "RESERVED_WORDS"
  };
}

