
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int IDENTIFIER = 78;
  public static final int TIMES = 9;
  public static final int REAL = 59;
  public static final int MINUS_EQUALS = 12;
  public static final int LESS_THAN = 18;
  public static final int PACKED = 55;
  public static final int TYPE = 68;
  public static final int READ = 58;
  public static final int GREATER_THAN = 17;
  public static final int CONST = 36;
  public static final int UNTIL = 69;
  public static final int ASSIGNMENT = 29;
  public static final int RPAREN = 3;
  public static final int DOUBLE = 75;
  public static final int LPAREN = 2;
  public static final int DIV_EQUALS = 13;
  public static final int FALSE = 41;
  public static final int PLUS_EQUALS = 11;
  public static final int NOT = 23;
  public static final int NIL = 53;
  public static final int ARRAY = 30;
  public static final int VAR = 70;
  public static final int SHIFT_RIGHT_EQUALS = 28;
  public static final int INLINE = 49;
  public static final int THEN = 65;
  public static final int GOTO = 46;
  public static final int RECORD = 60;
  public static final int CHARACTER = 77;
  public static final int MOD = 10;
  public static final int SHIFT_LEFT = 25;
  public static final int NUMBER = 74;
  public static final int WRITE = 73;
  public static final int TRUE = 67;
  public static final int PLUS = 6;
  public static final int NOT_EQUALS = 16;
  public static final int WHILE = 71;
  public static final int CHAR = 35;
  public static final int BOOLEAN = 32;
  public static final int LONGINT = 52;
  public static final int SHORTINT = 63;
  public static final int DO = 37;
  public static final int FOR = 43;
  public static final int DIV = 8;
  public static final int DOWNTO = 38;
  public static final int ELSE = 39;
  public static final int PROCEDURE = 56;
  public static final int INT = 50;
  public static final int EOF = 0;
  public static final int SHIFT_RIGHT = 26;
  public static final int TIMES_EQUALS = 14;
  public static final int FUNCTION = 45;
  public static final int GREATER_EQUALS_THAN = 19;
  public static final int XTRING = 76;
  public static final int REPEAT = 61;
  public static final int LABEL = 51;
  public static final int MINUS = 7;
  public static final int IN = 48;
  public static final int OR = 21;
  public static final int SET = 62;
  public static final int error = 1;
  public static final int IF = 47;
  public static final int OF = 54;
  public static final int END = 40;
  public static final int FILE = 42;
  public static final int RBRACKET = 5;
  public static final int GREATER_LESS_THAN = 20;
  public static final int BEGIN = 31;
  public static final int CASE = 34;
  public static final int FORWARD = 44;
  public static final int STRING = 64;
  public static final int SHIFT_LEFT_EQUALS = 27;
  public static final int PROGRAM = 57;
  public static final int BYTE = 33;
  public static final int AND = 22;
  public static final int TO = 66;
  public static final int LBRACKET = 4;
  public static final int WITH = 72;
  public static final int XOR = 24;
  public static final int EQUALS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "PLUS",
  "MINUS",
  "DIV",
  "TIMES",
  "MOD",
  "PLUS_EQUALS",
  "MINUS_EQUALS",
  "DIV_EQUALS",
  "TIMES_EQUALS",
  "EQUALS",
  "NOT_EQUALS",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_EQUALS_THAN",
  "GREATER_LESS_THAN",
  "OR",
  "AND",
  "NOT",
  "XOR",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "SHIFT_LEFT_EQUALS",
  "SHIFT_RIGHT_EQUALS",
  "ASSIGNMENT",
  "ARRAY",
  "BEGIN",
  "BOOLEAN",
  "BYTE",
  "CASE",
  "CHAR",
  "CONST",
  "DO",
  "DOWNTO",
  "ELSE",
  "END",
  "FALSE",
  "FILE",
  "FOR",
  "FORWARD",
  "FUNCTION",
  "GOTO",
  "IF",
  "IN",
  "INLINE",
  "INT",
  "LABEL",
  "LONGINT",
  "NIL",
  "OF",
  "PACKED",
  "PROCEDURE",
  "PROGRAM",
  "READ",
  "REAL",
  "RECORD",
  "REPEAT",
  "SET",
  "SHORTINT",
  "STRING",
  "THEN",
  "TO",
  "TRUE",
  "TYPE",
  "UNTIL",
  "VAR",
  "WHILE",
  "WITH",
  "WRITE",
  "NUMBER",
  "DOUBLE",
  "XTRING",
  "CHARACTER",
  "IDENTIFIER"
  };
}

